baseURL = "https://bhykes.github.io/Bio-Mainroad"
title = "Bioinformatics Practice"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
publishDIR = "docs"
contentDIR = "content"
layoutDir = "layouts"
canonifyURLs = true

[Author]
    name = "Bioinformatics Site"
    bio = "Words"
    avatar = "./img/rnaseq-0-quantification-large.png"


[Params]
    subtitle = "Scientific Site" # Subtitle of your site
    description = "Description of this Site" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
