baseURL = "https://bhykes.github.io/Bio-Mainroad"
title = "Bioinformatics Site"
languageCode= "en-us"
paginate = "10"
theme = "mainroad"
publishDIR = "docs"
disqusShortname = ""
googleAnalytics = ""

[Author]
	name = "John Doe Nut"
	bio = "Short Bio"
	avatar = "img/RNASeq.png"

[Params]
	subtitle = "Everything you need"
	description = "Provide information for published data"
	opengraph = true
	leftsidebar = false
	authorbox = true
	post_navigation = true

[Params.widgets]
	search = true
	recent_articles = true
	categories = true
	tags = true
